# Generated by Django 2.2.4 on 2019-08-05 11:34

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20190805_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to=detection.models.upload_location),
        ),
    ]
